"""
scripts/generate_report.py
--------------------------
Generates a markdown report from the weekly picks CSVs.

Scans output/runs/ for CSVs matching today's date, groups them by
universe and mode, and writes picks_YYYYMMDD.md alongside them.

Usage:
    python scripts/generate_report.py
    python scripts/generate_report.py --date 20260427 --output-dir output/runs
"""

import argparse
import re
from datetime import date
from pathlib import Path

import pandas as pd


def parse_csv_name(filename: str):
    """
    Extract (universe_label, mode) from a filename like:
        nifty_50_20260427_returns.csv
        etf_india_2026_20260427_sharpe.csv
    Returns (universe_label, mode) or None if no match.
    """
    match = re.match(r"^(.+?)_(\d{8})_(returns|sharpe|sortino)\.csv$", filename)
    if not match:
        return None
    universe_raw = match.group(1)
    mode         = match.group(3)
    label        = universe_raw.replace("_", " ").title()
    return label, mode


def build_table(csv_path: Path) -> list:
    df = pd.read_csv(csv_path, index_col=0)

    if "rank" not in df.columns or "final_score" not in df.columns:
        return ["_No rank/score columns found._", ""]

    df = df[["rank", "final_score"]].dropna().sort_values("rank")

    lines = [
        "| Rank | Ticker | Final Score |",
        "|------|--------|-------------|",
    ]
    for ticker, row in df.iterrows():
        lines.append(
            f"| {int(row['rank'])} | {ticker} | {row['final_score']:.4f} |"
        )
    lines.append("")
    return lines


def generate(output_dir: Path, date_str: str) -> str:
    # Discover all CSVs for this date
    pattern   = f"*_{date_str}_*.csv"
    csv_files = sorted(output_dir.glob(pattern))

    if not csv_files:
        return f"# Weekly Momentum Picks — {date_str}\n\n_No CSVs found for this date._\n"

    # Group by universe label
    universe_data: dict = {}
    for csv_path in csv_files:
        parsed = parse_csv_name(csv_path.name)
        if not parsed:
            continue
        label, mode = parsed
        universe_data.setdefault(label, {})[mode] = csv_path

    mode_order = ["returns", "sharpe", "sortino"]

    lines = [
        f"# Weekly Momentum Picks — {date_str}",
        "",
    ]

    for universe_label in sorted(universe_data.keys()):
        modes = universe_data[universe_label]
        lines.append(f"## {universe_label}")
        lines.append("")

        for mode in mode_order:
            if mode not in modes:
                continue
            lines.append(f"### {mode.capitalize()}")
            lines.extend(build_table(modes[mode]))

        lines.append("---")
        lines.append("")

    # Footer
    universe_list = ", ".join(sorted(universe_data.keys()))
    lines.append(f"*Generated by momentum engine — universes: {universe_list}*")
    lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate markdown report from weekly picks CSVs."
    )
    parser.add_argument(
        "--date",
        default=date.today().strftime("%Y%m%d"),
        help="Date string YYYYMMDD (default: today)",
    )
    parser.add_argument(
        "--output-dir",
        default="output/runs",
        help="Directory containing CSVs (default: output/runs)",
    )
    args = parser.parse_args()

    output_dir  = Path(args.output_dir)
    report_text = generate(output_dir, args.date)
    report_path = output_dir / f"picks_{args.date}.md"

    report_path.write_text(report_text, encoding="utf-8")
    print(f"Report saved → {report_path}")


if __name__ == "__main__":
    main()
